name: efficient-agent
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blas=1.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cupti=11.8.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - idna=3.10
  - importlib_metadata=8.5.0
  - ipykernel=6.25.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=3.20.3
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.3.1
  - magma=2.8.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - ninja=1.12.1
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openblas=0.3.28
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.12
  - python_abi=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=26.2.0
  - readline=8.2
  - scikit-learn=1.3.0
  - six=1.17.0
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - agentlego==0.2.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - astor==0.8.1
      - attrs==24.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - distro==1.9.0
      - docopt==0.6.2
      - einops==0.8.0
      - environs==9.5.0
      - fairscale==0.4.13
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.55.3
      - fsspec==2024.10.0
      - func-timeout==4.3.5
      - google-auth==2.37.0
      - google-auth-oauthlib==1.2.1
      - grpcio==1.68.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.25.1
      - humanfriendly==10.0
      - importlib-metadata==8.0.0
      - ipython==8.12.3
      - jiter==0.8.2
      - jmespath==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.23.1
      - mat4py==0.6.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - milvus-lite==2.4.10
      - milvus-model==0.2.6
      - mistune==3.0.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmpretrain==1.2.0
      - model-index==0.1.11
      - modelindex==0.0.2
      - multiprocess==0.70.15
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nltk==3.8.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.20.1
      - openai==1.48.0
      - openapi-pydantic==0.5.1
      - opencv-python==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - pillow==11.1.0
      - pip-tools==7.4.1
      - pipdeptree==2.23.0
      - pipreqs==0.5.0
      - protobuf==4.23.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycocotools==2.0.8
      - pycryptodome==3.21.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.19.1
      - pymilvus==2.4.6
      - pyparsing==3.2.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2023.4
      - pyyaml==6.0.2
      - rapidfuzz==3.11.0
      - referencing==0.35.1
      - regex==2023.8.8
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.5
      - scipy==1.11.2
      - seaborn==0.12.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - setuptools==60.2.0
      - shapely==2.0.6
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - thefuzz==0.22.1
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.2.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.65.2
      - transformers==4.40.0
      - triton==3.1.0
      - tzdata==2024.2
      - ujson==5.10.0
      - uvicorn==0.34.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - word2number==1.1
      - yapf==0.43.0
      - yarg==0.1.9
