debug: False
object_detection:
  - name: glip_atss_swin-t_b_fpn_dyhead_pretrain_obj365
    type: TextToBbox
    device: 0
    threshold: 0.5
  - name: glip_atss_swin-l_fpn_dyhead_16xb2_ms-2x_funtune_coco
    type: TextToBbox
    device: 1
    threshold: 0.7
vqa:
  - name: ofa-base_3rdparty-zeroshot_vqa
    type: VQA
    device: 1
  - name: blip2-opt2.7b_3rdparty-zeroshot_vqa
    type: VQA
    device: 0
llm:
  - name: meta-llama/Meta-Llama-3.1-8B-Instruct
    url: https://api.deepinfra.com/v1/openai
    cost: 8000
    temperature: 0
    prompt: You are a helpful assistant. You need to answer the question and keep it as short and simple as possible, without any explainations. For example, if the question is about the capital of France, you answer 'Paris'. If the question is about a certain number, return only the number.
  - name: meta-llama/Llama-3.3-70B-Instruct
    url: https://api.deepinfra.com/v1/openai
    cost: 70000
    temperature: 0
    prompt: You are a helpful assistant. You need to answer the question and keep it as short and simple as possible, without any explainations. For example, if the question is about the capital of France, you answer 'Paris'. If the question is about a certain number, return only the number.